# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltc_to_btc', models.FloatField()),
                ('eth_to_btc', models.FloatField()),
                ('eth_to_ltc', models.FloatField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HuoBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc', models.FloatField()),
                ('ltc', models.FloatField()),
                ('eth', models.FloatField()),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
