# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDifference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_e_price', models.FloatField(verbose_name='BTC-E价格')),
                ('huobi_price', models.FloatField(verbose_name='火币价格')),
                ('price_difference', models.FloatField(verbose_name='差价')),
                ('ctiem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
