# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pricedifference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedifference',
            name='data_type',
            field=models.IntegerField(choices=[(1, 'LTC/BTC'), (3, 'ETH/LTC'), (2, 'ETH/BTC')], default=1, verbose_name='数据类型'),
            preserve_default=False,
        ),
    ]
