# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170619_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=128)),
                ('is_download', models.BooleanField(default=False)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pricedifference',
            name='data_type',
            field=models.IntegerField(choices=[(1, 'LTC/BTC'), (2, 'ETH/BTC'), (3, 'ETH/LTC')], verbose_name='数据类型'),
        ),
    ]
